repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
    - id: check-added-large-files
    - id: check-merge-conflict
    - id: end-of-file-fixer
      exclude: '\.(svg|xml)$'
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
    - id: check-yaml
      args: [--allow-multiple-documents]
    - id: check-executables-have-shebangs
    - id: check-case-conflict
    - id: mixed-line-ending
      args: [--fix=lf]
      exclude: '\.(svg|xml)$'
    - id: detect-aws-credentials
      args: ['--allow-missing-credentials']
    - id: detect-private-key
